# SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause

obj-$(CONFIG_LUA) += lua-core.o lua-lib.o

lua-core-y := \
	lapi.o \
	lcode.o \
	ldebug.o \
	ldo.o \
	ldump.o \
	lfunc.o \
	lgc.o \
	llex.o \
	lmem.o \
	lobject.o \
	lopcodes.o \
	lparser.o \
	lstate.o \
	lstring.o \
	ltable.o \
	ltm.o \
	lundump.o \
	lvm.o \
	lzio.o

lua-lib-y := \
	lauxlib.o \
	lbaselib.o \
	ldblib.o \
	ltablib.o \
	lstrlib.o \
	loadlib.o \
	linit.o
